name = "real-estate-note"
pages_build_output_dir = "./public"
compatibility_date = "2024-02-26"

[[d1_databases]]
binding = "DB"
database_name = "real-estate-db"
database_id = "41599b93-23a2-4cc9-ad90-886be537058c"

[[d1_databases]]
binding = "JEJU_DB"
database_name = "real-estate-db"
database_id = "41599b93-23a2-4cc9-ad90-886be537058c"